name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t ecommerce_app .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run tests inside Docker
        run: |
          docker build -t ecommerce_app .
          docker run --rm --entrypoint python ecommerce_app manage.py test

  deploy:  
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # only deploy on main branch
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-d3158svdiees73ahqneg/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json"
